/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d570849b87f357c3c4a60b5
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection } from '@angular/fire/firestore';
import { Observable } from 'rxjs';

// Import Services
import { FilmService } from '../../services/film.service';
import { FilmMakerService } from '../../services/film-maker.service';
import { ActorService } from '../../services/actor.service';

import { Film } from '../../domain/manage_film_example_db/film';
import { Actor } from '../../domain/manage_film_example_db/actor';
import { FilmMaker } from '../../domain/manage_film_example_db/film-maker';

// START - USED SERVICES
/**
* FilmService.create
*	@description CRUD ACTION create
*
* FilmService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* FilmMakerService.list
*	@description CRUD ACTION list
*
* ActorService.list
*	@description CRUD ACTION list
*
* FilmService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a  Film
 */
@Component({
    selector: 'app-film-edit',
    templateUrl: 'film-edit.component.html',
    styleUrls: ['film-edit.component.css']
})
export class FilmEditComponent implements OnInit {
    item: any = {};
    itemDoc: AngularFirestoreDocument<Film>;
    isNew: Boolean = true;
    formValid: Boolean;

    listCast: Actor[];
    listFilmMaker: FilmMaker[];


    constructor(
        private filmService: FilmService,
        private filmmakerService: FilmMakerService,
        private actorService: ActorService,
        private route: ActivatedRoute,
        private location: Location) {
        // Init list
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.isNew = false;
                this.itemDoc = this.filmService.get(id);
                this.itemDoc.valueChanges().subscribe(item => this.item = item);

            }
            // Get relations
            this.actorService.list().subscribe(list => this.listCast = list);
            this.filmmakerService.list().subscribe(list => this.listFilmMaker = list);
        });
    }


    /**
     * Check if an Actor is in  cast
     *
     * @param {string} id Id of Actor to search
     * @returns {boolean} True if it is found
     */
    containActor(id: string): boolean {
        if (!this.item.cast) return false;
        return this.item.cast.indexOf(id) !== -1;
    }

    /**
     * Add Actor from Film
     *
     * @param {string} id Id of Actor to add in this.item.cast array
     */
    addActor(id: string) {
        if (!this.item.cast)
            this.item.cast = [];
        this.item.cast.push(id);
    }

    /**
     * Remove an Actor from a Film
     *
     * @param {number} index Index of Actor in this.item.cast array
     */
    removeActor(index: number) {
        this.item.cast.splice(index, 1);
    }

    /**
     * Save Film
     *
     * @param {boolean} formValid Form validity check
     * @param Film item Film to save
     */
    save(formValid: boolean): void {
        this.formValid = formValid;
        if (formValid) {
            if (this.isNew) {
                // Create
                this.filmService.create(this.item);
                this.isNew = false;
            } else {
                // Update
                this.filmService.update(this.itemDoc, this.item);
            }
            this.goBack();
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }

}
